### PR TITLE
Raw key witness encoding

### PR DESCRIPTION
**Pull request by halseth**
See proposed BIP change: https://github.com/Roasbeef/bips/pull/33

To allow verification of the group key, we encode the `raw internal key` as well as the signature over the `asset_id` in the witness of the minting transaction. This lets the verifier derive the group key and verify the signature at genesis.

Rem questions:
- [ ] To allow deriving the group key for a second tranche (having a different `asset_id` than was used to create the group key, we must somehow reference the original `asset_id`?
- [ ] As mentioned in #91 we could change the digest that is signed. Not determined yet what is the best approach here.

### CODE REVIEW

**Comment by halseth** [comment]
> Awesome to see the new commits @halseth. Any github comments to contextualize the new commits? We're targeting this PR for v0.2 and I'm wondering what else your PR needs for completion.

@dstadulis I'm working on finalizing the BIP in parallel with the implementation here. I think we have settled on something that works now and I'll try to implement that next week.

Any specific cut-off date for v0.2?

**Comment by dstadulis** [comment]
> Any specific cut-off date for v0.2?

2023-03-10

**Comment by Roasbeef** [comment]
I think this is still relevant and just needs a rebase? 

The other thing we need to do here is ensure that we can handle the version upgrade, as w'ell now have another version with slightly updated verification logic.

**Comment by dstadulis** [comment]
> think this is still relevant and just needs a rebase?

@halseth can you update?

**Comment by halseth** [comment]
@dstadulis @Roasbeef We should agree on the BIP changes first, I rebased https://github.com/Roasbeef/bips/pull/35 that one is ready to merge

**Comment by dstadulis** [comment]
> should agree on the BIP changes first, I rebased [Roasbeef/bips#35](https://github.com/Roasbeef/bips/pull/35) that one is ready to merge

now that's merged, is it possible to finalize the code so it's ready for review?

**Pull request closed without merging**
