### PR TITLE
rpc: Extend GetInfo RPC

### LINKED ISSUE #311: Extend getinfo RPC responses to include more comprehensive `tapd` information
#220 created the getinfo RPC.  Extending this command with other useful information like

- information about the lnd node `tapd` is paired with
- Universe connection status
- chain state / syncing
- [your idea here]

Please add comments to the issue for additional fields your use case would benefit from, with a short motivation description.

### PR DESCRIPTION
**Pull request by natalypeyioti**
This PR extends GetInfo RPC endpoint with the following info:
lnd identity pubkey, node alias, block height, block hash, synced to chain

This is an example response of the `getinfo` cli command with the current changes:

```
{
    "version":  "0.2.0-alpha commit=v0.2.0-94-g1f8dd8a-dirty",
    "lnd_version":  "0.16.2-beta",
    "network":  "signet",
    "lnd_identity_pubkey":  "031498adfc0ddd11d07b78f53230efe0986bea4278932749b95d18ccba42f0c6cf",
    "node_alias":  "031498adfc0ddd11d07b",
    "block_height":  148284,
    "block_hash":  "0000001b5aa637a8ca512471f11b4da1b1086a9e4519d953db2dd07e8c4062e4",
    "synced_to_chain":  true
}
```

TODO:

- universe federation
- universe stats

fixes #311

### CODE REVIEW

**Comment by ben2077** [comment]
Maybe i can take it？

**Comment by dstadulis** [comment]
> May i take this？

go for it, @ben2077

**Comment by dstadulis** [comment]
@ben2077 if you'd like the updated feature in v0.3-alpha, If you can deliver before end of next week, it can be included in the RC tagging.

**Comment by ben2077** [comment]
> @ben2077 if you'd like the updated feature in v0.3-alpha, If you can deliver before end of next week, it can be included in the RC tagging.

i will get it done.

**Comment by ben2077** [comment]
https://github.com/lightninglabs/taproot-assets/pull/554

**Comment by guggero** [comment]
Replaced by https://github.com/lightninglabs/taproot-assets/pull/554.

**Pull request closed without merging**
