### PR TITLE
chore: fix typos

### PR DESCRIPTION
**Pull request by GoodDaisy**
fix some typos

### CODE REVIEW

**Review by ffranr — CHANGES_REQUESTED** [review]
Looks good! Thanks for your contribution.

Please squash all commits into a single commit. Commit message can be:
```
multi: fix typos
```

**Review by GeorgeTsagk — APPROVED** [review]
Lgtm, pending the commit squash that @ffranr mentions :)

**Comment by GoodDaisy** [comment]
@ffranr @GeorgeTsagk thanks for your reviews.

**Review by guggero — APPROVED** [review]

**Review by ffranr — APPROVED** [review]
Thank you!

**Pull request merged**
