### PR TITLE
Improve coin selection unit tests

### PR DESCRIPTION
**Pull request by guggero**
Fixes https://github.com/lightninglabs/taproot-assets/issues/124.

### CODE REVIEW

**Comment by jharveyb** [comment]
Found some issues (in the unit tests) revealed by these test changes.

Put up a branch that could get pulled into this PR: https://github.com/lightninglabs/taproot-assets/tree/coin-selection-test-fixes

**Review by jharveyb — CHANGES_REQUESTED** [review]
See above comment

**Comment by guggero** [comment]
Thanks for the review and the fixes. I took over the commit with the group anchor improvement.

> IIUC the timeout would occur for any signal since the method call was complete.

That was kind of on purpose. We explicitly expect the `LeaseCoins` method not to be called. I agree that the timeout would occur on any other channel as well. But IMO selecting on the `listSignals` a second time doesn't really change that?

**Comment by jharveyb** [comment]
> That was kind of on purpose. We explicitly expect the `LeaseCoins` method not to be called. I agree that the timeout would occur on any other channel as well. But IMO selecting on the `listSignals` a second time doesn't really change that?

Ah, fair enough - so any of the 3 calls timing out is sufficient.

**Review by jharveyb — APPROVED** [review]
LGTM, coverage go up 🚀

**Review by Roasbeef — APPROVED** [review]
LGTM 🎉

**Pull request merged**
