### PR TITLE
taprpc: remove `js` build tag for `taprpc`, `assetwalletrpc` & `universerpc`

### PR DESCRIPTION
**Pull request by ViktorTigerstrom**
This PR removes the requirement of setting the `js` build tag when accessing the JSON callbacks for the `taprpc`, `assetwalletrpc` & `universerpc` packages. 
We've previously removed the `js` build tag requirement when using the JSON callbacks for the other LiT sub-servers, and this PR ensures that the `taproot-assets` doesn't require it either.

Happy to address any feedback :)!

### CODE REVIEW

**Comment by guggero** [comment]
Thanks for the PR! Content looks good to me, though I noticed we forgot to add the `mintrpc` package to the `PACKAGES` variable in the `gen_protos.sh` script. Should we add that in a commit of this PR as well?

**Comment by ViktorTigerstrom** [comment]
Thanks a lot for the review @guggero! Good catch, I've added `mintrpc` now as well :)!

**Review by ellemouton — APPROVED** [review]
Very nice 🔥

**Comment by ViktorTigerstrom** [comment]
Thanks a lot for the review @ellemouton!

**Review by guggero — APPROVED** [review]
LGTM :tada:

**Pull request merged**
