### PR TITLE
multi: rename RPC AssetLeaf proof field to account for transfer proofs

### PR DESCRIPTION
**Pull request by ffranr**
The field is now used to hold transfer proofs. This PR corrects the field name to account for that fact.

This PR needs to be merged first: https://github.com/lightninglabs/taproot-assets/pull/637
(To avoid rebase delay.)

### CODE REVIEW

**Review by Roasbeef — APPROVED** [review]
LGTM 📘

**Comment by jharveyb** [comment]
Draft to block merging or planning to add more?

**Comment by ffranr** [comment]
@jharveyb It was in draft to block merging. But ready for review + merge now!

**Review by jharveyb — APPROVED** [review]
LGTM 🚀

**Pull request merged**
