### PR TITLE
version: bump to version v0.5.0-alpha.rc1

### PR DESCRIPTION
**Pull request by guggero**
Prepare for tagging a first RC of `v0.5.0-alpha`.

To be merged **AFTER** https://github.com/lightninglabs/taproot-assets/pull/1209.

Requesting review from the whole team to share the joy of achieving this milestone.

### CODE REVIEW

**Comment by dstadulis** [comment]
+1 to merge #1221, after CI passes for https://github.com/lightninglabs/taproot-assets/pull/1209 and is approved by reviewers
```
rpc error: code = DeadlineExceeded desc = context deadline exceeded
        	Test:       	TestLightningTerminal/test_custom_channels
```

**Comment by guggero** [comment]
> Is this instance of Context deadline being exceeded possibly a flake?

No, it's because #1221 hasn't been merged yet.

**Comment by jharveyb** [comment]
Confirmed that this is using the same field as the previous RC cycle.

**Review by gijswijs — APPROVED** [review]
LFG! :fire:

**Review by dstadulis — APPROVED** [review]
✅ Merge sign! LFG! 🏴

**Review by GeorgeTsagk — APPROVED** [review]

**Pull request merged**
