### PR TITLE
Accept price deviation ppm configuration

### PR DESCRIPTION
**Pull request by lukegao209**

### CODE REVIEW

**Comment by guggero** [comment]
You don't need to open new pull requests for each change... You can just change the commits with some git rebase commands: https://hackernoon.com/beginners-guide-to-interactive-rebasing-346a3f9c3a6d

**Comment by lukegao209** [comment]
> You don't need to open new pull requests for each change... You can just change the commits with some git rebase commands: https://hackernoon.com/beginners-guide-to-interactive-rebasing-346a3f9c3a6d

I’m not very familiar with Go and the project conventions yet, but I’ll get better at it moving forward

**Comment by dstadulis** [comment]
Thanks for the code contribution! As mentioned, rebasing the PRs will make tracking the change requests easiest for everyone.

This'll be a helpful feature!

**Review by guggero — APPROVED** [review]
Thanks, LGTM :tada: Going to squash commits on merge.

**Pull request merged**
