### PR TITLE
sqlc: bump version

### PR DESCRIPTION
**Pull request by guggero**
Fixes https://github.com/lightninglabs/taproot-assets/issues/831.

### CODE REVIEW

**Comment by guggero** [comment]
This PR bumps the `etcd` dependencies to a newer version, which causes the `grpc-gateway/v2` library to be bumped as well, which results in a diff in the `*.swagger.json` files. I hope that doesn't affect the API generator, otherwise we might need to roll back that change (or update the API generator). We'll know once we merge this PR to `main` and the nightly API generator job runs.
FYI @jamaljsr.

**Comment by ffranr** [comment]
> We'll know once we merge this PR to main and the nightly API generator job runs.

I wasn't aware of that job. Where is it defined please @guggero ?

**Comment by guggero** [comment]
The code is here: https://github.com/lightninglabs/lightning-api-ng
The actual job is in a private repo, I'll send you the link offline.

**Comment by jamaljsr** [comment]
Thanks for the heads up @guggero. 

I just tested locally and thankfully it doesn't break the build. However, it's no longer detecting the REST Type and Placement for the fields that are in the `body` of the request messages. It's showing `unknown` for these fields.

image
 
I'll work on a PR to resolve the issue. It shouldn't be too difficult.

**Review by jharveyb — APPROVED** [review]
Thanks for picking this up! LGTM

**Pull request merged**
