### PR TITLE
multi: add proof courier addr to CLI, fix gRPC max message size, fix linter

### PR DESCRIPTION
**Pull request by guggero**
Fixes https://github.com/lightninglabs/taproot-assets/issues/608.

### CODE REVIEW

**Review by ffranr — APPROVED** [review]
Nice :100:

**Comment by Roasbeef** [comment]
Thing is, we'll run into this in short order, as the issue is we don't have pagination.

**Comment by guggero** [comment]
> Thing is, we'll run into this in short order, as the issue is we don't have pagination.
> 
> EDIT: looked the recv limit is pretty wumbo, which should hold us over, but do we want to continue sending over these gobs of data over w/o pagination?

I agree, this isn't the long-term fix. But since we had different max sizes and the same constant copied everywhere, I think we should still apply this fix just for clarity's sake.

**Review by jharveyb — APPROVED** [review]
Looks good! Didn't find any spots where the constant wasn't replaced.

**Comment by MaxBipal** [comment]
Cool

**Pull request merged**
