### PR TITLE
tchrpc: change FundChannel endpoint to POST

### PR DESCRIPTION
**Pull request by GeorgeTsagk**
Closes https://github.com/lightninglabs/taproot-assets/issues/1219

### CODE REVIEW

**Comment by V0nMis3s** [comment]
Hi @GeorgeTsagk, thank you for addressing the issue so quickly! However, I noticed that the changes in this PR directly modify the `taprpc/tapchannelrpc/tapchannel.pb.gw.go` file, which, as indicated in the first line (`Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.`), is an auto-generated file. 
Direct edits to this file are not recommended because:
1. These changes will be overwritten the next time the file is regenerated using `protoc`.
2. Maintaining changes directly in generated files makes it harder to track and ensure consistency across versions.

### Proposed Structural Solution
Instead of directly modifying the `.pb.gw.go` file, the appropriate place to make these changes is in the `.proto` file (`taprpc/tapchannelrpc/tapchannel.proto`). Specifically:
1. Add the explicit method annotation to the `FundChannel` RPC method.
2. Regenerate the gateway code by running `protoc` with the necessary flags, which will update the `.pb.gw.go` file automatically.

This approach ensures that:
- The `FundChannel` method is correctly mapped to a `POST` in the REST API.
- The generated files remain consistent with the source `.proto` definitions.
- The changes are maintainable and won't be accidentally overwritten.

Please let me know what you think!

**Comment by GeorgeTsagk** [comment]
Hey @V0nMis3s, thanks for taking a look at the PR

> Instead of directly modifying the .pb.gw.go file, the appropriate place to make these changes is in the .proto file (taprpc/tapchannelrpc/tapchannel.proto). Specifically:

This was actually automated and was generated by running `make rpc` (check the [Makefile](https://github.com/lightninglabs/taproot-assets/blob/main/Makefile#L253-L255) section). The only change that had to be made was in the [`tapchannel.yaml`](https://github.com/lightninglabs/taproot-assets/blob/main/taprpc/tapchannelrpc/tapchannel.yaml) file, which we use to map the rpc methods to rest endpoints

**Review by ffranr — APPROVED** [review]

**Comment by V0nMis3s** [comment]
Thank you for the explanation! I assumed the mapping was automatically handled by the default rules of grpc-gateway, and I didn’t realize the tapchannel.yaml file was being used to map the RPC methods to REST endpoints. Thanks for pointing that out!

**Review by gijswijs — APPROVED** [review]
LGTM :tada:

**Pull request merged**
