### PR TITLE
Strict forwarding pt.2

### PR DESCRIPTION
**Pull request by GeorgeTsagk**
## Description 

In a [previous PR](https://github.com/lightninglabs/taproot-assets/pull/1144) we added strict forwarding support, meaning that an invoice that asks for asset X may only be settled if the HTLCs are carrying asset X. We did not think of strict forwarding protection for btc invoices being paid for with asset HTLCs.

## Solution

In this PR we extend the `AuxInvoiceManager` with an extra check, which cancels the HTLCs that are paying to this invoice if the invoice is a btc invoice, but the HTLCs are carrying assets.

### Related Issues
Closes https://github.com/lightninglabs/taproot-assets/issues/1239

### CODE REVIEW

**Comment by GeorgeTsagk** [comment]
Will add some Litd itest coverage too

**Review by Roasbeef — APPROVED** [review]
LGTM 🏆

**Comment by Roasbeef** [comment]
We'll merge this after the `litd` itests are more stable.

**Comment by GeorgeTsagk** [comment]
Since this is breaking the current expected behavior from LitD itests, we are not going to see a green `Lit tests` check

Refer to the respective LitD PR for the correct state of the itests
https://github.com/lightninglabs/lightning-terminal/pull/916

**Comment by GeorgeTsagk** [comment]
[LitD itests](https://github.com/lightninglabs/lightning-terminal/actions/runs/12313829849/job/34369541395?pr=916) are green, merging this

**Pull request merged**
